### ISSUE TITLE
Week 2 Team ticket

### ISSUE THREAD

**Issue by Reinhardtlotter** [CalrethonOfMirkwood/ZONKNATION#25]
Reinhardt:

- [ ] [Api for positive message](https://github.com/CalrethonOfMirkwood/ZONKNATION/issues/23)s
- [ ] [Resource page with database(needs finished database and accounts from other members)](https://github.com/CalrethonOfMirkwood/ZONKNATION/issues/18)

Valerie and Sophie: 

- [ ] [Finish profiles ](https://github.com/CalrethonOfMirkwood/ZONKNATION/issues/20)

Soren:

- [ ] [File uploads(for picture posts](https://github.com/CalrethonOfMirkwood/ZONKNATION/issues/24))
